flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
  - discord-hs-0.2.1
  - pipes-4.3.5
  - bytestring-0.10.8.2
  - aeson-1.0.2.1
  - vector-0.11.0.0
  - primitive-0.6.1.0
  - HUnit-1.6.0.0
  - http-client-tls-0.3.5.1
  - config-ini-0.2.1.1
  - megaparsec-6.2.0
resolver: lts-9.5
